= Specification of the _<Project_Name>_ Application =

NOTE: Content inside tags like <Project_Name> should be changed by your 
own project's values. additionally, delete all the tips before generating your document.


_<Team_Name>_ _<Team_Email>_

:imagesOrderManagement: images/

:toc:
:toclevels: 4
:numbered:

== Use Cases ==
_<This chapter contains the definition of the business logic of the application.>_


TIP: The business logic is divided between the logic present in the services and the logic present in the client. If the logic implemented in the client is more complex than the dialogue flow, a simple service call or a confirmation dialogue, the logic may also be defined in a use case or a use case function. We differentiate between use cases in the client and service use cases using the stereotypes Client UC and Service UC

// tag::UseCases[]

=== Business Component BCO_<Component_Name>_Management ===
_<Insert here a diagram explaining your component's use cases (actors should be present)>_

image::{imagesOrderManagement}business_component_ComponentName_management.svg[caption="Figure 2: ", title="Business Component _<Component_Name>_ Management", alt="Business Component _<Component_Name>_ Management"]

_<Explain here the functionality of your component>_



==== Use Case "UC_Manage_<Component_Name>" ====


[cols="v,v" options=compact]
|====
2+| _<Explain here the functionalities of this use case>_
|Actors | _<List the actors involved in this use case>_  
|Usage | _<Type of event that triggered it: "Automatic" if it was the system, or "Manual" if it was a user >_
|Precondition | _<List the conditions or events needed for executing this use case>_
|====

_<Explain here the execution workflow followed by the events listed on "Precondition">_

.Standard workflow: _<Event_Name1>_
. _<Explain step>_
. _<Explain step>_
. _<Explain step>_

.Alternative workflow: _<Event_Name2>_
. _<Explain step>_
. _<Explain step>_
. _<Explain step>_


==== Client Use Case "UC_Create_<Component_Name>" ====

TIP: Make distinction between use cases related to clients (or users) and the ones related to the system.

[cols="v,v" options=compact]
|====
2+| _<Explain here the functionalities of this use case related to the client or user>_

|Actors | _<List the actors involved in this use case>_ 
|Usage | _<Type of event that triggered it: "Automatic" if it was the system, or "Manual" if it was a user >_
|Preconditions |
_<List the conditions or events needed for executing this use case>_
|====

.Standard workflow: _<Event_Name1>_
. _<Explain step>_
. _<Explain step>_
. _<Explain step>_

.Alternative workflow: _<Event_Name2>_
. _<Explain step>_
. _<Explain step>_
. _<Explain step>_

// end::UseCases[]
== Data Model ==
// tag::DataModel[]

_<This chapter contains the data model of the application.>_

TIP: This data model is primarily defined by diagrams. Textual documentation 
is added for the entity types, attributes and relations, for which the diagrams 
are not sufficient as documentation. This should be the exception

TIP: There is not only a data model for data stored in a database. If necessary, 
transient internal data models may also be defined in this chapter.


=== Model Component MCO_<Component_Name> ===
_<Insert here a diagram explaining the data model of your component. It is normally
 a class diagram that defines the attributes of each component and the entities 
 involved.>_

image::{imagesOrderManagement}mco_ComponentName.svg[caption="Figure 3: ", title="Model Component MCO_<Component_Name>", alt="Model Component MCO_<Component_Name>"]

TIP: Use the sufix ATT_ for defining attributes, entities with ETY_ and MCO_ for model components.

_<List the entities shown on the diagram:>_

==== Entity Type ETY_<Entity_Name1> ====
_<Explain here the attributes of this entity, what encapsulates and in which case it is needed.>_

==== Entity Type ETY_<Entity_Name2> ====
_<Explain here the attributes of this entity, what encapsulates and in which case it is needed.>_

// end::DataModel[]
== External Interfaces ==
// tag::ExternalInterfaces[]


=== External Interface EIF_Manage_<Component_Name> ===
_<This section defines the external interfaces required by the application or provided by the application.>_

TIP: All services provided by the server application are documented here. Since most of the services 
are quite simple CRUD (Create, Read, Update, Delete) services, they will be defined in diagrams alone.
Additional documentation is supplied where needed.

TIP: If an external interface is already defined and documented (most probably in the sending or receiving system),
 it does not need to be documented again: A reference to the existing documentation is sufficient. This documentation 
 may even be (within limits) technical. The benefit is, aside from the effort to document the interface, to have a 
 single source of truth for the interface.

_<Insert here a diagram describing the external interfaces and the events contained by it. Events may contain multiple entities which should be described.   >_

image::{imagesOrderManagement}eif_manage_ComponentName.svg[caption="Figure 4: ", title="External Interface EIF_Manage_<Component_Name>", alt="External Interface EIF_Manage_<Component_Name>"]

This external interface provides the following operations using the different
interface entity types:

- _<Event_Name1>_: See _UC_Manage_Component_Name_, Scenario _<Event_Name1>_ .
- _<Event_Name2>_: See _UC_Manage_Component_Name_, Scenario _<Event_Name2>_ .
- _<Event_Name3>_: See _UC_Manage_Component_Name_, Scenario _<Event_Name3>_ .

// end::ExternalInterfaces[]
