=  User Stories

:toc:

Content

== Epic: Invite friends
=== US: create invite for friends

Epic: Invite friends

As a guest I want to create an dinner event by entering date and time and adding potential guest by their emails so that each potential guests receives a email in order to confirm or decline my invite.

===== Acceptance criteria
- only date and time in future possible and both required
- only valid email addresses: text@text.xx, one entered email-address is required
- if AGB are not checked, an error message is shown

===== Wireframes
...

==== US: handle invite

As an invited guest I would like to receive an email - after somebody as invited me - with the option to accept or decline the invite so that the system knows about my participation

===== AC:
. the mail contains the following information about the invite
  .. who has invited
  .. who else is invited
  .. date and time of the invite
  .. button to accept or decline
  .. after pressing the buttons the system will store the status (yes/no) of my invite

=== US: calculate best table

As a guest I would like the system to check (1 hour before my invite) all my invites and to reserve a table fitting the number of accepted users

===== Details
Pseudo-algorithm for reservation:
Find table for given date and time where seats of guests >= Count of invited guests plus one. In case no results, decline request and show error message to user. In case of any result, make a reservation for table....
For each decline of a guest remove guest and search with reduced number for new table. In case table is found, reserve it and remove reservation from previous table. In case not, do not change reservations.

=== US: find table by reservation info

As a ?guest/waiter? I would like to search by reference number or email address for my reserved table in order to know the table for my visit. (when arriving at the restaurant)

===== AC:
. After entering the email the systems shows the number of the table. In case no reservation found, a message is shown.
. Entered email address could be email of inviter or any invited guest.

=== US: cancel invite
Epic: Invite friends

As a guets who has sent an invite I want to be able to cancel my previous invite

===== AC:
...

== Epic: Digital Menu
=== US: filter menu

As a guest I want to filter the menu so that I only see the dishes I am interested in

===== AC:
. the guest can filter by
 .. type: starter | main dish | dessert; XOR; if nothing is selected all are shown (default value)
 .. veggy (yes|no|does not matter (default))
 .. vegan (yes|no|does not matter (default))
 .. rice (yes|no|does not matter (default))
 .. curry (yes|no|does not matter (default))
 .. noodle (yes|no|does not matter (default))
 .. price (range)
 .. ratings (range)
 .. my favorite (yes|no|does not matter (default))
 -- free text (search in title and description)
. the guest can sort by price asc, rating asc
. after setting the filter only dishes are shown which fulfills those criteria
. by pressing the button reset filter all filter are reset to the initial value
. by pressing the filter button the filter is applied [or is it triggered after each change?]

=== US: Define order

As a guest I want to define my order by selecting dishes from the menu

===== AC:
- The guest can add each dish to the order
- In case the guest adds the same dish multiple times, a counter is increased for this dish
- The guest can remove the dish from the order
- The guest can add for each main dish the type of meat (pork, chicken, tofu)
- The guest can add for each dish a free-text-comment
- After adding/removing any dish the price is calculated including VAT

=== US: Order the order

AC: I receive a mail containing my order with all dishes

=== US: Cancel order
AC: ...

== Epic: Rate by twitter









checklist:

talk about:

 - who?
 - what?
 - why (purpose)
 - why (objective)
 - what happens outside the software
 - what might go wrong
 - any question or assumptions (write them down) , DoR should check that those sections are empty.
 - is there any better solution?
 - how (technical perspective)
 - do a rough estimate
 - check INVEST
