@startuml

class EIF_Manage_Component_Name <<External Interface>> {
  }


package "Save Entity_Name" #DDDDDD {

  class IET_Save_Entity_Name <<Interface Entity Type>> {
    see ETY_Entity_Name
  }

  class IET_Entity_Name <<Interface Entity Type>> {
    see ETY_Entity_Name
  }
}

package "Delete Entity_Name" #DDDDDD {

  class IET_Delete_Entity_Name <<Interface Entity Type>> {
    IAT_Entity_Name1_ID: DTY_Number
  }

}

package "Find Entity_Name" #DDDDDD {

  class IET_Find_Entity_Name <<Interface Entity Type>> {
    IAT_Entity_Name1_ID: DTY_Number [0..1]
    IAT_Entity_Name2_ID: DTY_Number [0..1]
    IAT_Entity_Name3_Token: DTY_Text [0..1]
    IAT_Entity_Name4: DTY_Text [0..1]
    IAT_Component_Name_Token: DTY_Text [0..1]
  }

  class IET_Paginated_List_of_Entity_Name1s <<Interface Entity Type>> {
    see ETY_Entity_Name
  }

}

EIF_Manage_Component_Name --|> IET_Find_Entity_Name : <<uses input parameter>>
EIF_Manage_Component_Name --|> IET_Save_Entity_Name : <<uses input parameter>>
EIF_Manage_Component_Name --|> IET_Delete_Entity_Name : <<uses input parameter>>
EIF_Manage_Component_Name --|> IET_Paginated_List_of_Entity_Name1s : <<provides output parameter>>
EIF_Manage_Component_Name --|> IET_Entity_Name : <<provides output parameter>>

@enduml
