@startuml

class EIF_Manage_Booking <<External Interface>> {
  }


package "Save Order" #DDDDDD {

  class IET_Save_Order <<Interface Entity Type>> {
    see ETY_Order
  }

  class IET_Order <<Interface Entity Type>> {
    see ETY_Order
  }
}

package "Delete Order" #DDDDDD {

  class IET_Delete_Order <<Interface Entity Type>> {
    IAT_Order_ID: DTY_Number
  }

}

package "Find Orders" #DDDDDD {

  class IET_Find_Order <<Interface Entity Type>> {
    IAT_Order_ID: DTY_Number [0..1]
    IAT_Invited_Guest_ID: DTY_Number [0..1]
    IAT_Host_Token: DTY_Text [0..1]
    IAT_Email_Address: DTY_Text [0..1]
    IAT_Booking_Token: DTY_Text [0..1]
  }

  class IET_Paginated_List_of_Orders <<Interface Entity Type>> {
    see ETY_Order
  }

}

EIF_Manage_Booking --|> IET_Find_Order : <<uses input parameter>>
EIF_Manage_Booking --|> IET_Save_Order : <<uses input parameter>>
EIF_Manage_Booking --|> IET_Delete_Order : <<uses input parameter>>
EIF_Manage_Booking --|> IET_Paginated_List_of_Orders : <<provides output parameter>>
EIF_Manage_Booking --|> IET_Order : <<provides output parameter>>

@enduml
