@startuml

class EIF_Manage_User <<External Interface>> {
  }


package "Find User" #DDDDDD {

  class IET_Find_User <<Interface Entity Type>> {
    IAT_Username: DTY_Text [0..1]
    IAT_Password: DTY_Text [0..1]
    IAT_Email: DTY_Text [0..1]
    IAT_User_Role_ID: DTY_Number [0..1]
  }

  class IET_Paginated_List_of_Users <<Interface Entity Type>> {
    see ETY_User
  }
}

package "Delete User" #DDDDDD {

  class IET_Delete_User <<Interface Entity Type>> {
    IAT_User_ID: DTY_Number
  }

}

package "Save User" #DDDDDD {

  class IET_Save_User <<Interface Entity Type>> {
    see ETY_User
  }

  class IET_User <<Interface Entity Type>> {
    see ETY_User
  }

}

EIF_Manage_User --|> IET_Find_User : <<uses input parameter>>
EIF_Manage_User --|> IET_Save_User : <<uses input parameter>>
EIF_Manage_User --|> IET_Delete_User : <<uses input parameter>>
EIF_Manage_User --|> IET_Paginated_List_of_Users : <<provides output parameter>>
EIF_Manage_User --|> IET_User : <<provides output parameter>>

@enduml
