@startuml
ACR_ActorName1 << Actor >>
ACR_ActorName2  << Actor >>
ACR_ActorName3 << Actor >>
rectangle "<<Business Component>>\nBCO_<Component_Name>_Management" #DDDDDD {
  (<<Client UC>>\nUC_Create_<Component_Name>) as UC_Create_ComponentName
  (<<Service UC>>\nUC_Manage_<Component_Name>) as UC_Manage_ComponentName
  (<<Service UC>>\nUC_Request_<Service_Name>) as UC_Request_ServiceName

ACR_ActorName1 ..|> UC_Create_ComponentName : <<uses>>
ACR_ActorName2 ..|> UC_Create_ComponentName : <<uses>>

UC_Create_ComponentName ..|> UC_Manage_ComponentName : <<uses>>

ACR_ActorName3 ..|> UC_Request_ServiceName : <<uses>>
}
@enduml
