@startuml

  class ETY_Entity_Name1 {
    ...
  }
  note bottom: in MCO_Entity_Name1

  class ETY_Entity_Name2 {
    ...
  }

class ETY_Component_Name {
  ATT_ID: DTY_Number
  ATT_Attribute_Name1: DTY_Text_120
  ATT_Attribute_Name2: DTY_Text_255
  ATT_Attribute_Name3: DTY_Text_60
}

class ETY_Entity_Name3 {
  ATT_ID: DTY_Number
  ATT_Attribute_Name4: DTY_Text_120
  ATT_Attribute_Name5: DTY_Boolean
}

ETY_Component_Name "0..1" -- "0..*" ETY_Entity_Name3: has roles >

ETY_Component_Name "0..1" -- "0..*" ETY_Entity_Name1: Inviter of Entity_Name1 >

ETY_Component_Name "0..*" -- "0..*"  ETY_Entity_Name2: favorite Entity_Name2 >


@enduml
