@startuml
:ACR_Actor_Name1: << Actor >> as ACR_Actor_Name1
:Actor_Name2: << Actor >> as Actor_Name2
:Actor_Name3: << Actor >> as Actor_Name3

:Actor_Parent: << Actor >> as Actor_Parent
:Actor_Name4: << Actor >> as Actor_Name4
:ACR_System_Project_Name: << Actor >> as ACR_System_Project_Name

Actor_Name3 <|-- ACR_Actor_Name1
Actor_Name3 <|-- Actor_Name2
Actor_Parent <|--  Actor_Name4
Actor_Parent <|--  Actor_Name3

@enduml
