@startuml
ACR_Reserving_Guest << Actor >>
ACR_Invitee << Actor >>
ACR_System_MyThaiStar << Actor >>
rectangle "<<Business Component>>\nBCO_Order_Management" #DDDDDD {
  (<<Client UC>>\nUC_Create_Order) as UC_Create_Order
  (<<Service UC>>\nUC_Manage_Order) as UC_Manage_Order
  (<<Service UC>>\nUC_Manage_Order_Line) as UC_Manage_Order_Line
  (<<Service UC>>\nUC_Request_Twitter_Rating) as UC_Request_Twitter_Rating

ACR_Reserving_Guest ..|> UC_Create_Order : <<uses>>
ACR_Invitee ..|> UC_Create_Order : <<uses>>

UC_Create_Order ..|> UC_Manage_Order : <<uses>>
UC_Create_Order ..|> UC_Manage_Order_Line : <<uses>>

ACR_System_MyThaiStar ..|> UC_Request_Twitter_Rating : <<uses>>
}
@enduml
