@startuml

  class ETY_Booking {
    ...
  }
  note bottom: in MCO_Booking

  class ETY_Dish {
    ...
  }

  note bottom: in MCO_Menu

class ETY_User {
  ATT_ID: DTY_Number
  ATT_UserName: DTY_Text_120
  ATT_Password: DTY_Text_255
  ATT_Email: DTY_Text_60
}

class ETY_User_Role {
  ATT_ID: DTY_Number
  ATT_Name: DTY_Text_120
  ATT_Active: DTY_Boolean
}

ETY_User "0..1" -- "0..*" ETY_User_Role: has roles >

ETY_User "0..1" -- "0..*" ETY_Booking: Inviter of bookings >

ETY_User "0..*" -- "0..*"  ETY_Dish: favorite dishes >


@enduml
